# .github/workflows/build.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt

      - name: Install runtime dependencies
        run: pip install -r requirements.txt

      - name: Run Linux x86 build
        run: |
          chmod +x build/build_linux_x86.sh
          build/build_linux_x86.sh

      - name: Verify build output
        run: |
          echo "Contents of dist/:"
          ls -l dist
          echo "Executable file type:"
          file dist/main || file dist/type_simulator
