name: E2E Typing Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # xfonts-base supplies the missing ISO10646 font that xterm expects
          sudo apt-get install -y xvfb xterm xdotool xfonts-base vim nano

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pexpect pytest

      - name: Run E2E tests via wrapper
        run: |
          chmod +x tests/run_tests.sh
          tests/run_tests.sh
